Controllers/TordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DFA_CORE.Models;
using NToastNotify;

namespace DFA_CORE.Controllers
{
    public class TordersController : Controller
    {
        private readonly TE_Core_MVCContext _context;
        private readonly ILogger<TordersController> _logger;
        private readonly IToastNotification _toastNotification;
        public TordersController(ILogger<TordersController> logger, IToastNotification toastNotification, TE_Core_MVCContext context)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _context = context;

        }

        // GET: Torders
        public async Task<IActionResult> Index()
        {
              return View(await _context.Torders.ToListAsync());
        }

        // GET: Torders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Torders == null)
            {
                return NotFound();
            }

            var torder = await _context.Torders
                .FirstOrDefaultAsync(m => m.Oid == id);
            if (torder == null)
            {
                return NotFound();
            }

            return View(torder);
        }

        // GET: Torders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Torders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Oid,Oname,Oitem,Oquant")] Torder torder)
        {
            if (ModelState.IsValid)
            {
                _context.Add(torder);
                await _context.SaveChangesAsync();
                _toastNotification.AddSuccessToastMessage("Order Added successfully");

                return RedirectToAction(nameof(Index));
            }
            return View(torder);
        }

        // GET: Torders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Torders == null)
            {
                return NotFound();
            }

            var torder = await _context.Torders.FindAsync(id);
            if (torder == null)
            {
                return NotFound();
            }
            return View(torder);
        }

        // POST: Torders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Oid,Oname,Oitem,Oquant")] Torder torder)
        {
            if (id != torder.Oid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(torder);
                    await _context.SaveChangesAsync();
                    _toastNotification.AddWarningToastMessage("Order updated successfully");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TorderExists(torder.Oid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(torder);
        }

        // GET: Torders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Torders == null)
            {
                return NotFound();
            }

            var torder = await _context.Torders
                .FirstOrDefaultAsync(m => m.Oid == id);
            if (torder == null)
            {
                return NotFound();
            }

            return View(torder);
        }

        // POST: Torders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Torders == null)
            {
                return Problem("Entity set 'TE_Core_MVCContext.Torders'  is null.");
            }
            var torder = await _context.Torders.FindAsync(id);
            if (torder != null)
            {
                _context.Torders.Remove(torder);
            }
            
            await _context.SaveChangesAsync();
            _toastNotification.AddErrorToastMessage("Order deleted successfully");
            return RedirectToAction(nameof(Index));
        }

        private bool TorderExists(int id)
        {
          return _context.Torders.Any(e => e.Oid == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DFA_CORE</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DFA_CORE.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DFA_CORE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Torders" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DFA_CORE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>